// <auto-generated />
using AdminPanel.Const;
using AdminPanel.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AdminPanel.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20180422183748_init2")]
    partial class init2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AdminPanel.Models.tblUser", b =>
                {
                    b.Property<long>("PKID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsActive");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<int>("Role");

                    b.HasKey("PKID");

                    b.ToTable("tblUser");
                });

            modelBuilder.Entity("AdminPanel.Models.tblUserVerification", b =>
                {
                    b.Property<long>("PKID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EmailCode");

                    b.Property<string>("PhoneCode");

                    b.Property<DateTime?>("SentEmailCodeTime");

                    b.Property<DateTime?>("SentPhoneCodeTime");

                    b.Property<long>("UserId");

                    b.HasKey("PKID");

                    b.HasIndex("UserId");

                    b.ToTable("tblUserVerification");
                });

            modelBuilder.Entity("AdminPanel.Models.tblUserVerification", b =>
                {
                    b.HasOne("AdminPanel.Models.tblUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
